#!/bin/bash
# Git cleanup commands to squash commits and clean history
# Run these commands manually after reviewing changes

echo "⚠️  WARNING: These commands will rewrite git history!"
echo "Make sure you have a backup before proceeding."
echo ""
echo "Commands to run:"
echo ""
echo "# 1. Interactive rebase to squash commits by phase"
echo "git rebase -i --root"
echo ""
echo "# In the editor, organize commits like this:"
echo "# pick <first-commit> Initial setup"
echo "# squash <commits...> Phase 1: Core implementation"
echo "# squash <commits...> Phase 2: Advanced features"
echo "# squash <commits...> Phase 3: Creative tools"
echo "# squash <commits...> Phase 4: Production resilience"
echo "# squash <commits...> Phase 5: Repository cleanup"
echo ""
echo "# 2. Update author information (replace with your details)"
echo 'git filter-branch --env-filter \'
export GIT_AUTHOR_NAME="Your Name"
export GIT_AUTHOR_EMAIL="your.email@example.com"
export GIT_COMMITTER_NAME="Your Name"
export GIT_COMMITTER_EMAIL="your.email@example.com"
\' --tag-name-filter cat -- --branches --tags'
echo ""
echo "# 3. Remove co-authored-by lines"
echo "git filter-branch --msg-filter 'sed \"/Co-Authored-By:/d\"' HEAD"
echo ""
echo "# 4. Force push (only if you're sure!)"
echo "git push --force origin main"
echo ""
echo "# Alternative: Create a new clean branch"
echo "git checkout -b main-clean"
echo "git push origin main-clean"